name = "StateSpaceGrids"
uuid = "39e37ee1-5ccb-4cc5-be0a-4fd9eff95447"
authors = ["hotzsauce <githotz@gmail.com>"]
version = "0.0.1"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
EllipsisNotation = "1.6.0"
Interpolations = "0.14"
Reexport = "1.2.2"
julia = "1.7"
